project:
  type: book

book:
  title: "Angewandte Datenanalyse für die öffentliche Verwaltung"
  chapters:
    - index.qmd
    - Modul_1.qmd
    - Modul_2.qmd
    - Modul_3.qmd
    - Modul_4.qmd
    - team.qmd
  navbar:
    background: white

format:
  html:
    theme: flatly
    number-depth: 0

suppress-bibliography: true



